// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static bool isRelease() {
    return const bool.fromEnvironment('dart.vm.product');
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (isRelease()) {
          return android;
        } else {
          return androidDev;
        }
      case TargetPlatform.iOS:
        if (isRelease()) {
          return ios;
        } else {
          return iosDev;
        }
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get("PRD_FIREBASE_WEB_API_KEY"),
    appId: dotenv.get("PRD_FIREBASE_WEB_APP_ID"),
    messagingSenderId: dotenv.get("PRD_FIREBASE_MESSAGING_SENDER_ID"),
    projectId: dotenv.get("PRD_FIREBASE_PROJECT_ID"),
    authDomain: dotenv.get("PRD_FIREBASE_WEB_AUTH_DOMAIN"),
    storageBucket: dotenv.get("PRD_FIREBASE_STORAGEBUCKET"),
    measurementId: dotenv.get("PRD_FIREBASE_WEB_MEASUREMENT_ID"),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get("PRD_FIREBASE_ANDROID_API_KEY"),
    appId: dotenv.get("PRD_FIREBASE_ANDROID_APP_ID"),
    messagingSenderId: dotenv.get("PRD_FIREBASE_MESSAGING_SENDER_ID"),
    projectId: dotenv.get("PRD_FIREBASE_PROJECT_ID"),
    storageBucket: dotenv.get("PRD_FIREBASE_STORAGEBUCKET"),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get("PRD_FIREBASE_IOS_API_KEY"),
    appId: dotenv.get("PRD_FIREBASE_IOS_APP_ID"),
    messagingSenderId: dotenv.get("PRD_FIREBASE_MESSAGING_SENDER_ID"),
    projectId: dotenv.get("PRD_FIREBASE_PROJECT_ID"),
    storageBucket: dotenv.get("PRD_FIREBASE_STORAGEBUCKET"),
    iosClientId: dotenv.get("PRD_FIREBASE_IOS_CLIENT_ID"),
    iosBundleId: dotenv.get("PRD_FIREBASE_IOS_BUNDLE_ID"),
  );

  static FirebaseOptions androidDev = FirebaseOptions(
    apiKey: dotenv.get("DEV_FIREBASE_ANDROID_API_KEY"),
    appId: dotenv.get("DEV_FIREBASE_ANDROID_APP_ID"),
    messagingSenderId: dotenv.get('DEV_FIREBASE_MESSAGING_SENDER_ID'),
    projectId: dotenv.get('DEV_FIREBASE_PROJECT_ID'),
    storageBucket: dotenv.get('DEV_FIREBASE_STORAGEBUCKET'),
  );

  static FirebaseOptions iosDev = FirebaseOptions(
    apiKey: dotenv.get("DEV_FIREBASE_IOS_API_KEY"),
    appId: dotenv.get('DEV_FIREBASE_IOS_APP_ID'),
    messagingSenderId: dotenv.get('DEV_FIREBASE_MESSAGING_SENDER_ID'),
    projectId: dotenv.get('DEV_FIREBASE_PROJECT_ID'),
    storageBucket: dotenv.get('DEV_FIREBASE_STORAGEBUCKET'),
    iosClientId: dotenv.get("DEV_FIREBASE_IOS_CLIENT_ID"),
    iosBundleId: dotenv.get("DEV_FIREBASE_IOS_BUNDLE_ID"),
  );
}
